baseURL:
languageCode: en-us
title: Herzog Foundation
disableKinds:
  - taxonomy
  - taxonomyTerm
enableRobotsTXT: true
paginate: 1
params:
  twitter_user: kris_ray
  twitter_link: https://twitter.com/
  facebook_link: http://www.facebook.com/
  instagram_link: https://www.instagram.com/
  #google_analytics: UA-
  paid_for: Paid for by Language Goes Here
  form_endpoint: 123456
markup:
  goldmark:
    parser:
      autoHeadingID: false

menu:
  main:
    - name: About
      url: /#about
      weight: 10
    - name: What's Inside
      url: /#whats-inside
      weight: 20
    - name: Eligibility
      url: /#eligibility
      weight: 30
  footer:
    - name: About
      url: /#about
      weight: 10
    - name: What's Inside
      url: /#whats-inside
      weight: 20
    - name: Eligibility
      url: /#eligibility
      weight: 30
    - name: Contact Us
      url: /#
      weight: 40
